### ISSUE TITLE
How to output image?

### ISSUE THREAD

**Issue by jeremyworger** [avihuxp/WaveFunctionCollapse#3]
Hi there, super cool project! Sorry if this is a dumb question....but when I run the program it gives me this window: https://imgur.com/a/Q6Goc95
And the generation won't complete unless I repeatably close the window. How can I output a single image, or watch the generation in real time, and then save the image?  
Would you consider doing a small tutorial video as well?  Just showing how you can get different ouputs via the settings?

**Comment by avihuxp** [comment]
Hi! 
The windows you got are the program showing the progress of the collapse every few iterations, I updated the main function to receive 2 additional parameters, `render_iterations` and `render_video`, to make the usage more accessible from the command line, for more on these parameters, refer to the updated README ☺️ 
As for creating a small tutorial video, thank you for the suggestion! I've added this feature to the features list as a to-do item
